        # Generated by Django 5.0.1 on 2024-01-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0006_rename_name_user_username_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
